doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        profiling: false
        profiling_collect_backtrace: false

    orm:
        entity_managers:
            default:
                connection: default
                auto_mapping: false
                validate_xml_mapping: false
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                mappings:
                    AccessRequestDoctrine:
                        type: attribute
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/AccessRequest/Infrastructure/Doctrine/Entity'
                        prefix: 'App\AccessRequest\Infrastructure\Doctrine\Entity'
                        alias: AccessRequestDoctrine
                    SecurityDoctrine:
                        type: attribute
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/Security/Infrastructure/Doctrine/Entity'
                        prefix: 'App\Security\Infrastructure\Doctrine\Entity'
                        alias: SecurityDoctrine
                    TrackedJobDoctrine:
                        type: attribute
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/TrackedJob/Infrastructure/Doctrine/Entity'
                        prefix: 'App\TrackedJob\Infrastructure\Doctrine\Entity'
                        alias: TrackedJobDoctrine