framework:
    secret: '%env(APP_SECRET)%'
    http_method_override: false
    handle_all_throwables: true
    session:
        enabled: true
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
        cookie_secure: auto
        cookie_samesite: lax
        cookie_httponly: true
        cookie_lifetime: '%env(int:SESSION_COOKIE_LIFETIME)%'
        name: '%env(SESSION_COOKIE_NAME)%'
    serializer:
        enabled: true
    validation:
        enabled: true

when@dev:
    framework:
        profiler:
            collect: false
