api_platform:
    title: GrailJob Tracker API Platform
    version: 0.1.0
    defaults:
        stateless: false
    formats:
        json: ['application/json']
    docs_formats:
        jsonopenapi: ['application/vnd.openapi+json']
        html: ['text/html']
    exception_to_status:
        App\Shared\Application\Exception\ApplicationNotFound: 404
        App\Shared\Application\Exception\ApplicationConflict: 409
        App\Shared\Application\Exception\ApplicationBadRequest: 400
        App\Shared\Application\Exception\InvalidApplicationCommand: 422
        App\Shared\Application\Exception\ApplicationException: 400
        App\Shared\Domain\Exception\DomainException: 400


