doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        server_version: '16'
        profiling_collect_backtrace: '%kernel.debug%'
    orm:
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: false
        mappings:
            SecurityRecords:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Security/Infrastructure/Doctrine/Entity'
                prefix: 'App\Security\Infrastructure\Doctrine\Entity'
                alias: SecurityRecords
            TrackedJobRecords:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/TrackedJob/Infrastructure/Doctrine/Entity'
                prefix: 'App\TrackedJob\Infrastructure\Doctrine\Entity'
                alias: TrackedJobRecords
            AccessRequestRecords:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/AccessRequest/Infrastructure/Doctrine/Entity'
                prefix: 'App\AccessRequest\Infrastructure\Doctrine\Entity'
                alias: AccessRequestRecords


when@prod:
    doctrine:
        orm:
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system

